package com.orientdata.lookforcustomers.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import com.baidu.location.BDLocation;
import com.baidu.mapapi.search.core.PoiInfo;

import org.litepal.crud.DataSupport;

import java.io.Serializable;
// KEEP INCLUDES END

/**
 * Entity mapped to table ADDRESS_SEARCH_RECODE.
 */
public class AddressSearchRecode extends DataSupport implements Serializable {


    private static final long serialVersionUID = 2077061348358481540L;
    private Double longitude;
    private Double latitude;
    private String name;
    private String city;
    private String address;

    // KEEP FIELDS - put your custom fields here
	private int recodeType;



    public final static int FROM_LOCATION = 0x00;
	public final static int FROM_SEARCH = 0x01;
	public final static int FROM_RECODE = 0x02;
	public final static int SHOW_TIPS = 0x03;
	public final static int DELETE_ALL_ADDRESS = 0x99;
    // KEEP FIELDS END

    public AddressSearchRecode() {
    }

    public AddressSearchRecode(String address) {
        this.address = address;
    }

    public AddressSearchRecode(Double longitude, Double latitude, String name, String city, String address) {
        this.longitude = longitude;
        this.latitude = latitude;
        this.name = name;
        this.city = city;
        this.address = address;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    // KEEP METHODS - put your custom methods here
	public AddressSearchRecode(int recodeType) {
		this.recodeType = recodeType;
	}

	public AddressSearchRecode(BDLocation location) {
		this.recodeType = FROM_LOCATION;
		name = location.getAddrStr();
		city = location.getCity();
		address = location.getAddrStr();
		longitude = location.getLongitude();
		latitude = location.getLatitude();
	}

	public AddressSearchRecode(PoiInfo poiInfo) {
		recodeType = FROM_SEARCH;
		longitude = poiInfo.location.longitude;
		latitude = poiInfo.location.latitude;
		name = poiInfo.name;
		city = poiInfo.city;
		address = poiInfo.address;
	}

	public int getRecodeType() {
		return recodeType;
	}

	public void setRecodeType(int recodeType) {
		this.recodeType = recodeType;
	}
    // KEEP METHODS END

}
